services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 20.15.1
    image: admin-panel-server-dev-image:latest
    container_name: admin-panel-server-dev-container
    ports:
      - '8000:8000'
    env_file:
      - .env.develop
